export enum EventEnum {
  EVENT_OPEN_MISSION_LIST = "EVENT_OPEN_MISSION_LIST",
  EVENT_OPEN_RANKING = "EVENT_OPEN_RANKING",
  EVENT_OPEN_SHOP = "EVENT_OPEN_SHOP",
  OPPEN_MESSAGE = "OPPEN_MESSAGE",
  BUY_ITEM = "BUY_ITEM"
}